swagger: '2.0'
info:
  title: Meeting App API
  description: Meeting App API Gateway specification for Cloud Run backend (No Authentication Required)
  version: '1.0.0'
  
host: YOUR_GATEWAY_URL
basePath: /
schemes:
  - https

# Firebase認証の設定
securityDefinitions:
  firebase:
    authorizationUrl: "" # ここは空のままでOK
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/mac-sdo-hackathon" # ここ書き換える
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "mac-sdo-hackathon" # ここ書き換える

security:
  - firebase: []

# Cloud Run バックエンド設定
x-google-backend:
  address: https://meeting-app-387251040101.asia-northeast1.run.app
  path_translation: APPEND_PATH_TO_ADDRESS

paths:
  /:
    get:
      summary: Root endpoint
      description: ルートエンドポイント
      operationId: getRoot
      responses:
        '200':
          description: Successful response
          schema:
            type: object
  
  /health:
    get:
      summary: Health check
      description: 基本ヘルスチェック
      operationId: getHealth
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              status:
                type: string
                example: "healthy"
  
  /health/detailed:
    get:
      summary: Detailed health check
      description: 詳細ヘルスチェック
      operationId: getDetailedHealth
      responses:
        '200':
          description: Successful response
          schema:
            type: object
  
  /summarize-meeting:
    post:
      summary: Meeting summarization
      description: 会議要約
      operationId: summarizeMeeting
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              content:
                type: string
                description: 会議内容
      responses:
        '200':
          description: Successful response
          schema:
            type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
  
  /action-item-meeting:
    post:
      summary: Extract action items
      description: アクションアイテム抽出
      operationId: extractActionItems
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              content:
                type: string
                description: 会議内容
      responses:
        '200':
          description: Successful response
          schema:
            type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
  
  /dispute-argument-meeting:
    post:
      summary: Detect dispute
      description: 争い検出・仲裁
      operationId: detectDispute
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              content:
                type: string
                description: 会議内容
      responses:
        '200':
          description: Successful response
          schema:
            type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
  
  /tangent-topic-meeting:
    post:
      summary: Detect tangent
      description: 脱線検出
      operationId: detectTangent
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              content:
                type: string
                description: 会議内容
      responses:
        '200':
          description: Successful response
          schema:
            type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
  
  /visualize-mermaid-meeting:
    post:
      summary: Visualize with Mermaid
      description: Mermaid図可視化
      operationId: visualizeMermaid
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              content:
                type: string
                description: 会議内容
      responses:
        '200':
          description: Successful response
          schema:
            type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
  
  /recording-meeting:
    post:
      summary: Audio transcription
      description: 音声文字起こし（バイナリデータ送信）
      operationId: transcribeAudio
      consumes:
        - application/octet-stream
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
  
  /upload-audio:
    post:
      summary: Upload audio
      description: 音声アップロード（バイナリデータ送信）
      operationId: uploadAudio
      consumes:
        - application/octet-stream
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
  
  /audio/formats:
    get:
      summary: Get supported audio formats
      description: サポートされている音声形式の情報取得
      operationId: getSupportedFormats
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              formats:
                type: array
                items:
                  type: string
  
  /get-anniversary:
    post:
      summary: Get anniversary and icebreaker
      description: 記念日取得とアイスブレイク生成
      operationId: getAnniversary
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              date:
                type: string
                format: date
                description: 日付
      responses:
        '200':
          description: Successful response
          schema:
            type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
  
  /anniversary/today:
    get:
      summary: Get today's anniversary
      description: 今日の記念日取得
      operationId: getTodayAnniversary
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            type: object
  
  /anniversary/all:
    get:
      summary: Get all anniversaries
      description: 指定日のすべての記念日を取得
      operationId: getAllAnniversaries
      produces:
        - application/json
      parameters:
        - in: query
          name: date
          type: string
          format: date
          description: 日付
      responses:
        '200':
          description: Successful response
          schema:
            type: object
  
  /anniversary/random:
    get:
      summary: Get random anniversary
      description: ランダムな記念日を取得
      operationId: getRandomAnniversary
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            type: object
  
  /anniversary/statistics:
    get:
      summary: Get anniversary statistics
      description: 記念日データの統計情報を取得
      operationId: getStatistics
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            type: object
  
  /stats/usage:
    get:
      summary: Get API usage statistics
      description: API使用量統計（開発環境のみ）
      operationId: getUsageStats
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              usage:
                type: object
              note:
                type: string

# エラーレスポンス定義
definitions:
  Error:
    type: object
    properties:
      error:
        type: string
      message:
        type: string