services:
  # バックエンドAPI (Node.js Express)
  backend:
    build:
      context: ./functions
      dockerfile: Dockerfile.dev
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    container_name: meeting-app-backend
    restart: unless-stopped
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run dev -- --host 0.0.0.0
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ./functions:/app
      # - backend_node_modules:/app/node_modules  # node_modulesをコンテナ内に保持
    networks:
      - meeting-app-network

  # フロントエンド (React + Vite)
  frontend:
    build:
      context: ./llm-meeting
      dockerfile: Dockerfile.dev
    container_name: meeting-app-frontend
    restart: unless-stopped
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
      - VITE_API_BASE_URL=/api
    volumes:
      - ./llm-meeting:/app
    networks:
      - meeting-app-network
    depends_on:
      - backend

networks:
  meeting-app-network:
    driver: bridge

# volumes:
#   backend_node_modules:
#     name: backend_node_modules
#     driver: local
